#!/usr/bin/env python3
"""
plot_effectors.py
Dot-plot of the top-N candidate salivary effectors/toxins: one row per
protein, one column per curated functional category, dot size/color by
TPM. Reads directly from effector_candidates_ranked.tsv (no hardcoded
values) generated by effector_candidates.py.

Usage:
  python 06_effector_prioritization/plot_effectors.py [--top N]
"""

import argparse
import csv
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

BASE = Path(__file__).resolve().parent.parent
RANKED = BASE / "results" / "effector_candidates" / "effector_candidates_ranked.tsv"
FIG_DIR = BASE / "figures"

plt.rcParams.update({
    "font.family":       "Arial",
    "font.size":         11,
    "axes.titlesize":    12,
    "axes.labelsize":    11,
    "xtick.labelsize":   10,
    "ytick.labelsize":   9,
    "legend.fontsize":   10,
    "axes.linewidth":    0.8,
    "axes.spines.top":   False,
    "axes.spines.right": False,
    "figure.dpi":        150,
})

CATEGORY_LABELS = {
    "venom_protease": "Venom protease",
    "dpp4": "DPP4",
    "venom_carboxypeptidase": "Venom carboxypeptidase",
    "salivary_secreted": "Salivary secreted",
    "nos_salivary": "NO synthase",
    "laccase": "Laccase",
    "mucin": "Mucin",
    "phospholipase": "Phospholipase A2/B",
    "ef_hand_ca_binding": "EF-hand / Ca-binding",
    "gh28_gh5_cazy": "GH28/GH5 (CAZy)",
}


def load_candidates(top_n):
    rows = []
    with open(RANKED, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            rows.append(row)
    rows.sort(key=lambda r: (int(r["n_curated_matches"]), float(r["tpm"])), reverse=True)
    return rows[:top_n]


def short_label(row):
    gene = row.get("gene_name", "").strip()
    name = gene.split(" ", 1)[1] if gene and " " in gene else row["protein_id"]
    name = name.split("[")[0].strip()
    if len(name) > 45:
        name = name[:42] + "..."
    return f"{row['protein_id'].split('.')[0]}  {name}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--top", type=int, default=25)
    args = parser.parse_args()

    if not RANKED.exists():
        raise SystemExit(f"[ERROR] {RANKED} not found -- run effector_candidates.py first.")

    candidates = load_candidates(args.top)
    if not candidates:
        raise SystemExit("[ERROR] No candidates to plot.")

    categories = sorted({t for r in candidates for t in r["curated_terms"].split(";") if t})
    cat_x = {c: i for i, c in enumerate(categories)}
    labels = [short_label(r) for r in candidates]

    xs, ys, sizes, colors = [], [], [], []
    for i, r in enumerate(candidates):
        tpm = float(r["tpm"])
        for t in r["curated_terms"].split(";"):
            if not t:
                continue
            xs.append(cat_x[t])
            ys.append(i)
            sizes.append(20 + 180 * min(tpm, 50) / 50)
            colors.append(tpm)

    fig_h = max(4, 0.32 * len(candidates) + 1.2)
    fig, ax = plt.subplots(figsize=(8.5, fig_h))

    sca = ax.scatter(xs, ys, s=sizes, c=colors, cmap="viridis",
                      edgecolors="black", linewidths=0.4, zorder=3)

    ax.set_xticks(range(len(categories)))
    ax.set_xticklabels([CATEGORY_LABELS.get(c, c) for c in categories],
                        rotation=35, ha="right")
    ax.set_yticks(range(len(candidates)))
    ax.set_yticklabels(labels)
    ax.invert_yaxis()
    ax.set_xlim(-0.5, len(categories) - 0.5)
    ax.set_ylim(len(candidates) - 0.5, -0.5)
    ax.grid(axis="both", linestyle=":", linewidth=0.5, color="#cccccc", zorder=0)
    ax.set_title(f"Top {len(candidates)} candidate salivary effectors/toxins\n"
                 "(classical secretome AND curated toxin/effector term match)")

    cbar = fig.colorbar(sca, ax=ax, pad=0.02, fraction=0.04)
    cbar.set_label("TPM")

    fig.tight_layout()
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    png_path = FIG_DIR / "effector_candidates.png"
    tiff_path = FIG_DIR / "effector_candidates.tiff"
    fig.savefig(png_path, dpi=300)
    fig.savefig(tiff_path, dpi=600)
    print(f"Saved: {png_path}")
    print(f"Saved: {tiff_path}")


if __name__ == "__main__":
    main()
